comment:
  layout: header, changes, diff
codecov:
  branch: master
coverage:
  ignore:
  - charonrpc/*.pb.go
  - internal/model/*.pqt.go
  - charontest/.*.go
  notify:
    slack:
      default:
        threshold: '0'
        url: https://hooks.slack.com/services/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
  status:
    patch: false

