version: 2.1

commands:
  mkdir_working_directory:
    steps:
    - run:
        name: Initialize working directory
        working_directory: /
        command: |
          sudo mkdir -p /home/circleci/project/home/circleci/project/go/src/github.com/piotrkowalczuk/charon
          sudo chmod -R 777 /home/circleci/project/home/circleci/project/go/src/github.com/piotrkowalczuk/charon
executors:
  python-executor:
    docker:
    - image: cimg/python:3.12.6
    working_directory: /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
  swift-executor:
    docker:
      - image: swift:6.0
    working_directory: /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
  java-executor:
    docker:
    - image: cimg/openjdk:8.0.345
    working_directory: /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
  golang-executor:
    docker:
    - image: cimg/go:1.23.1
    environment:
      GOPATH: "/home/circleci/project/go"
      GOBIN:   "/home/circleci/go/bin"
    working_directory: /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
jobs:
  setup_golang:
    executor: golang-executor
    steps:
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Install dependencies
        command: go mod vendor
    - save_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
        paths:
        - "vendor"
  test_golang:
    docker:
    - image: cimg/go:1.23.1
    - image: cimg/postgres:9.6
      environment:
        POSTGRES_USER: test
        POSTGRES_DB: test
    working_directory: /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
    steps:
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Install tools
        command: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
          go install golang.org/x/tools/cmd/goimports@v0.25.0
          curl -L -O https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 
          mv test-reporter-latest-linux-amd64 /home/circleci/go/bin/test-reporter
          chmod +x /home/circleci/go/bin/test-reporter
          bash ./.circleci/scripts/install_protoc.sh linux
    - run:
        name: Generate protobuf
        command: bash ./.circleci/scripts/generate.sh golang
    - run:
        name: Check generated code for mismatch
        command: git diff --exit-code ./pb
#    - run:
#        name: Code Climate (before build)
#        command: test-reporter before-build
    - run:
        name: Run tests
        environment:
          CHAROND_POSTGRES_ADDRESS: "postgres://test@localhost/test?sslmode=disable"
        command: |
          mkdir -p /tmp/test-results/golang
          make test
          go tool cover -html=cover.out -o /tmp/test-results/golang/results.html
          cp results.xml /tmp/test-results/golang/results.xml
          pwd
          ls -lha
#          test-reporter format-coverage -d -t=gocov cover.out
#    - run:
#        name: Code Climate (after build)
#        command: |
#          cp cover.out c.out
#          test-reporter after-build --coverage-input-type=gocov
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
    - save_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
        paths:
        - "vendor"
  lint_protobuf:
    executor: golang-executor
    steps:
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Install protoc
        command: bash ./.circleci/scripts/install_protoc.sh linux
    - run:
        name: Install command line tools
        command: |
          go install github.com/ckaznocha/protoc-gen-lint@v0.3.0
    - run:
        name: insight
        command: |
          env
          pwd
          ls -lha ~/project
          ls -lha /home/circleci/go/bin
          ls -lha /home/circleci/project/go/src/github.com/piotrkowalczuk/charon
    - run:
        name: Lint protobuf
        command: bash ./.circleci/scripts/generate.sh lint
  build_golang:
    executor: golang-executor
    steps:
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Build
        command: |
          make build
    - store_artifacts:
        path: ./bin
    - persist_to_workspace:
        root: ./
        paths:
        - bin
  build_docker:
    docker:
    - image: docker:18.06.0-ce-git
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - setup_remote_docker:
        docker_layer_caching: true
        version: 18.06.0-ce
    - run:
        name: Docker build
        command: |
          docker build --build-arg VCS_REF=${VCS_REF} --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t piotrkowalczuk/charon:${CIRCLE_TAG:-latest} .
    - run:
        name: Docker save
        command: |
          docker save -o ./docker-image.tar piotrkowalczuk/charon:${CIRCLE_TAG:-latest}
    - persist_to_workspace:
        root: ./
        paths:
        - docker-image.tar
  publish_docker:
    docker:
    - image: docker:18.06.0-ce-git
    steps:
    - attach_workspace:
        at: ./
    - setup_remote_docker:
        docker_layer_caching: true
        version: 18.06.0-ce
    - run:
        name: Docker load
        command: |
          docker load < ./docker-image.tar
    - run:
        name: Docker login
        command: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - run:
        name: Docker push
        command: |
          docker push piotrkowalczuk/charon:${CIRCLE_TAG:-latest}
  generate_java:
    executor: java-executor
    steps:
    - mkdir_working_directory
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Install protoc
        command: bash ./.circleci/scripts/install_protoc.sh linux
    - run:
        environment:
          GOPATH: "/home/circleci/project/go"
        name: Generate protobuf
        command: bash ./.circleci/scripts/generate.sh java
  generate_python:
    executor: python-executor
    steps:
    - mkdir_working_directory
    - checkout
    - restore_cache:
        key: v1-golang-dependency-{{ checksum "go.sum" }}
    - run:
        name: Install python packages
        command: |
          python -m venv ./venv
          . venv/bin/activate
          pip install grpcio grpcio-tools twine
    - run:
        name: Install protoc
        command: bash ./.circleci/scripts/install_protoc.sh linux
    - run:
        name: Generate protobuf
        environment:
          GOPATH: "/home/circleci/project/go"
        command: |
          . venv/bin/activate
          bash ./.circleci/scripts/generate.sh python
    - save_cache:
        key: v1-python-dependency-{{ .Branch }}-{{ .Revision }}
        paths:
        - "venv"
        - "publish/python/github"
  publish_python:
    executor: python-executor
    steps:
    - mkdir_working_directory
    - checkout
    - run:
        name: Init VERSION.txt file
        command: make version
    - restore_cache:
        keys:
        - v1-python-dependency-{{ .Branch }}-{{ .Revision }}
    - run:
        name: Create package
        command: |
          cd publish/python
          python setup.py sdist
          python setup.py bdist_wheel
    - run:
        name: Upload to pypi
        command: |
          . ./venv/bin/activate
          twine upload ./publish/python/dist/*
  generate_swift:
    executor: swift-executor
    steps:
      - run:
          name: Initialize working directory
          working_directory: /
          command: |
            mkdir -p /home/circleci/project/home/circleci/project/go/src/github.com/piotrkowalczuk/charon
            chmod -R 777 /home/circleci/project/home/circleci/project/go/src/github.com/piotrkowalczuk/charon
            apt update
            apt install curl
      - checkout
      - restore_cache:
          key: v1-golang-dependency-{{ checksum "go.sum" }}
      - run:
          name: Install protoc
          command: bash ./.circleci/scripts/install_protoc.sh linux
      - run:
          name: Install protoc plugins for Swift
          command: |
            echo $PATH
            git clone https://github.com/grpc/grpc-swift-protobuf.git
            cd grpc-swift-protobuf
            swift build --product protoc-gen-swift
            swift build --product protoc-gen-grpc-swift
            cp .build/debug/protoc-gen-grpc-swift /usr/local/bin/
            cp .build/debug/protoc-gen-swift /usr/local/bin/
            cd ..
        
            # Verify gRPC Swift plugin installation
            protoc-gen-grpc-swift --version
      - run:
          name: Generate protobuf
          environment:
            GOPATH: "/home/circleci/project/go"
          command: |
            bash ./.circleci/scripts/generate.sh swift
workflows:
  version: 2
  generate:
    jobs:
    - setup_golang:
        filters:
          tags:
            only: /.*/
    - test_golang:
        context: codeclimate-charon
        requires:
        - setup_golang
        filters:
          tags:
            only: /.*/
    - lint_protobuf:
        requires:
        - setup_golang
        filters:
          tags:
            only: /.*/
    - build_golang:
        requires:
        - test_golang
        filters:
          tags:
            only: /.*/
    - build_docker:
        requires:
        - build_golang
        filters:
          tags:
            only: /.*/
    - publish_docker:
        context: hub.docker.com
        requires:
        - build_docker
        filters:
          branches:
            only: master
          tags:
            only: /^(v)?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
    - generate_python:
        requires:
        - lint_protobuf
        filters:
          tags:
            only: /.*/
    - generate_java:
        requires:
        - lint_protobuf
        filters:
          tags:
            only: /.*/
    - generate_swift:
        requires:
          - lint_protobuf
        filters:
          tags:
            only: /.*/
    - publish_python:
        context: twine
        requires:
        - build_golang
        - generate_python
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^(v)?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
